spring:
#  flyway:
#    baseline-on-migrate: true
  datasource:
    url: jdbc:h2:~/pipeline
    username: "admin1"
    password: "test1"
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      driver-class-name: "org.h2.Driver"
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.H2Dialect"
#    profiles:
#      active: rest
